apiVersion: v1
kind: Service
metadata:
  labels:
    p8s-app: node-exporter
  name: node-exporter-service
  namespace: monitoring
spec:
  selector:
    p8s-app: node-exporter
  type: NodePort
  ports:
  - name: node-exporter
    protocol: TCP
    port: 9100
    targetPort: node-exporter
