apiVersion: v1
kind: Service
metadata:
    name: app3-nginx-cip-service
    labels:
        app: app3-nginx-cip-service
spec:
    ports:
        - port: 80
    selector:
        app: app3-nginx-deployment
