groups:
- name: recording_rules
  rules:
  - record: instance:node_cpu:count
    expr: count without (cpu) (count without (mode) (node_cpu_seconds_total))

- name: different_eval_interval
  interval: 5s
  rules:
  - record: handler_instance:prometheus_http_request_duration_seconds_sum:rate5m
    expr: >
      rate(prometheus_http_request_duration_seconds_sum[5m])
  - record: handler_instance:prometheus_http_request_duration_seconds_count:rate5m
    expr: >
      rate(prometheus_http_request_duration_seconds_count[5m])
  - record: handler:prometheus_http_request_duration_seconds:mean5m
    expr: >
      sum without (instance) (
        handler_instance:prometheus_http_request_duration_seconds_sum:rate5m
      )
      /
      sum without (instance) (
        handler_instance:prometheus_http_request_duration_seconds_count:rate5m
      )
