apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: k8s
  name: alertmanager-service
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    port: 9093
    targetPort: web
  selector:
    alertmanager: k8s
    app: alertmanager
