- hosts: localhost
  become: true
  vars:
    java_packages:
      - java-1.8.0-openjdk
    jenkins_plugins:
      - configuration-as-code
      - blueocean
    jenkins_admin_username: admin@jenkins.cdk
    jenkins_admin_password: dontpushthisintoproduction
  tasks:
    - name: obtain jenkins public ip
      uri:
        url: http://169.254.169.254/latest/meta-data/public-ipv4
        return_content: yes
      register: public_ip
    - set_fact: jenkins_hostname="{{ public_ip.content }}"
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
