# Kubernetes Resource: Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: dev-ns-role
    namespace: dev
rules:
    - apiGroups: ["", "extensions", "apps"]
      resources: ["*"]
      verbs: ["*"]
    - apiGroups: ["batch"]
      resources:
          - jobs
          - cronjobs
      verbs: ["*"]
---
# Kubernetes Resource: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: dev-ns-rolebinding
    namespace: dev
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: dev-ns-role
subjects:
    - kind: Group
      namespace: dev
      name: eks-developer-group
